bean/Bean.go, pkg/service/HelmAppService.go, pkg/service/HelmAppServiceWrapper.go, pkg/service/K8sService.go, pkg/util/HelmServiceUtil.go
1) Some refactoring and bug fixes (refactoring before testing and bug fixes after testing)
2) Introduced 2 new app statuses -  "Hibernated" and "Partially Hibernated"
Fixes # https://github.com/devtron-labs/devtron/issues/1425
By hitting hibernate & un-hibernate APIs
=> fix : hibernate unhibernate refactoring and some bug fixes

pkg/service/K8sService.go, pkg/util/k8s/K8sUtil.go
App detail was failing for kubernetes version 1.25+. fixed that
=> App detail fatal fix for kubernetes version 1.25+

pkg/service/HelmAppService.go
Updated creation timestamp (z format) in resource tree fetch api.
=> fix: updated resource tree nodes creation timestamp

pkg/cluster/ClusterRepository.go, pkg/k8sInformer/K8sInformer.go
Address of pointer was accessed for fetching cluster
=> fix: external helm apps cache pointer fix

pkg/k8sInformer/K8sInformer.go
Adding filter on informer for saving only helm apps secret which are not superseded in informer
=> Informer memory

pkg/service/K8sService.go, pkg/util/k8s/K8sUtil.go
Helm apps deployed via No_GITOPS doesn't show PVC, this pr aims to fix that issue.
Fixes  [#3333](https://github.com/devtron-labs/devtron/issues/3333)
=> fix: handling pvc in resource tree, incorporated for helm apps

pkg/service/HelmAppService.go, pkg/service/K8sService.go, pkg/util/k8s/K8sUtil.go
Currently Helm apps with NO_GITOPS doesn't fetch child resources from CRDS, so this pr aims to fix that issue.
Fixes [#3271](https://github.com/devtron-labs/devtron/issues/3271)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Test Scenarios:- 
1. Deploying helm charts via helm to see all crd's child resources are visible or not.
2. Deploying devtron apps via helm  to see all crd's child resources are visible or not.
3. For previously deployed apps devtron/helm check is their crd's are visible or not.
=> fix: crd's child resources not visible for helm apps

api/router/router.go
Building health api for kubelink
=> Fix: health api for kubelink

pkg/service/HelmAppService.go, pkg/service/HelmAppService_test.go
Running Helm apps with --atomic flag and helm upgrade --install in case of upgrading the helm chart
=> Feature: run helm apps with --atomic in install case and helm upgrade --install in upgrade case

pkg/helmClient/client.go, pkg/service/HelmAppService.go
Fixes https://github.com/devtron-labs/devtron/issues/3660
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
```release-note
```
=> fix: manifest output is not in sync with selected chart version and wrong manifest coming in deployment history

pkg/service/HelmAppService.go
manifest object fetch requests are made parallely with configured batch size.
=> perf: manifest fetch in batching

pkg/service/HelmAppService.go
Fixed helm upgrade with install flag for helm apps
=> fixed: helm upgrade with install flag for helm apps

pkg/service/HelmAppService.go
logger romoved that was logging encrypted notes.txt
=> logger removed

error/constants.go, error/errorTypes.go, error/utils.go, pkg/helmClient/client.go, pkg/service/HelmAppService.go
Fixes :- https://github.com/devtron-labs/devtron/issues/4798
=> fix:5xx 4th iter

go.mod, go.sum, vendor/github.com/docker/docker/pkg/ioutils/readers.go, vendor/github.com/docker/docker/pkg/ioutils/writers.go, vendor/github.com/docker/docker/registry/config.go, vendor/modules.txt
Updated the versions for depenadbot security. 
Fixes #[4839](https://github.com/devtron-labs/devtron/issues/4839)
=> fix: dependabot version upgrade 

App.go, Main.go, wire_gen.go
Added the graceful shutdown
Fixes #
=> feat: graceful shutdown 

error/constants.go
External app wire set corrected
Fixes [#5033](https://github.com/devtron-labs/devtron/issues/5033)
=> fix: namespaceNotFoundErrorMsg fixed

go.mod, go.sum, pkg/service/HelmAppService.go, vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go, vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go, vendor/modules.txt, wire_gen.go
log.fatal removed 
Fixes #5054
=> common lib version upgrade

go.mod, go.sum, vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go, vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go, vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go, vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go, vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go, vendor/modules.txt
Fixes https://github.com/devtron-labs/devtron/issues/5254
```release-note
```
=> chore: common-lib upgrade for nats replicas

go.mod, go.sum, vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go, vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go, vendor/modules.txt
Updated Common Lib to f14be466613d
=> fix: Updated common lib 
